// AUTOGENERATED - DO NOT EDIT DIRECTLY
// typings for apps/web/content/articles/articles.pt-BR.json

export interface Article {
  slug: string;
  title: string;
  description: string;
  date: string;
  tags: string[];
  author: string;
  readingTime: string;
  canonical: string;
  cover: string;
}

export interface ArticlesPtBRJson {
  $schema: string;
  articles: Article[];
}

declare const value: ArticlesPtBRJson;
export default value;
