// AUTOGENERATED - DO NOT EDIT DIRECTLY
// typings for apps/web/content/photography/photography.json

export interface Photo {
  id: string;
  src: string;
  alt: string;
  date?: string;
  location?: string;
  timeOfDay?: string;
  occasion?: string;
  tags?: string[];
}

export interface Album {
  id: string;
  name: string;
  description: string;
  date: string;
  location?: string;
  cover?: string;
  photos: Photo[];
}

export interface PhotographyJson {
  $schema: string;
  albums: Album[];
}

declare const value: PhotographyJson;
export default value;
