// AUTOGENERATED - DO NOT EDIT DIRECTLY
// typings for apps/web/content/photography/photography.json

export interface Photo {
  id: string;
  src: string;
  alt: string;
  location?: string;
  date?: string;
  timeOfDay?: 'Dawn' | 'Morning' | 'Afternoon' | 'Golden Hour' | 'Night';
  occasion?: string;
  tags?: string[];
}

export interface PhotographyJson {
  $schema: string;
  photos: Photo[];
}

declare const value: PhotographyJson;
export default value;
